### ISSUE TITLE
PA Review: Registration/Tickets

### ISSUE THREAD

**Issue by MikeSalisbury** [MikeSalisbury/eventbright#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by MikeSalisbury** [comment]
create registration is functional (the register button); however, not sure how to display this is successful without a user profile page which shows the registrations.

**Comment by anastassia-b** [comment]
The registration works. Several notes:
- [x] It jumps to the bottom of the page on click.
- [x] You can add a small component on the event show page which says "You've registered for this event" as a way to show off this feature.

Optional
Since it redirects to the index page when I click "register", it takes a while to load and the user might not think that the button was clicked. You could add a loading icon.

**Comment by anastassia-b** [comment]
Optional Idea:
- [ ] Display ticket information for each event on the index, possibly like "Tickets Left: 3/100". Still keep the user's own tickets on the show page. 
- [x] Add "Price"/ "Cost"/USD to the total price.
- [x] Possibly remain on the show page after buying tickets.
- [x] Possibly distinguish between "my tickets" and total tickets. "Tickets: 1" is a bit ambiguous.
